import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
const migration=readFileSync(new URL('../supabase/migrations/20261002101527_record_review_service.sql',import.meta.url),'utf8');
test('Postgres: ownership, review authority, evidence, snapshots and publication separation',async()=>{
 const db=new PGlite();
 await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$; grant usage on schema auth to anon,authenticated; grant execute on function auth.uid() to anon,authenticated; create schema storage; create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]); create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text); alter table storage.objects enable row level security; grant usage on schema storage to authenticated; grant select,insert,delete on storage.objects to authenticated;`);
 await db.exec(migration);
 const owner='00000000-0000-4000-8000-000000000001',stranger='00000000-0000-4000-8000-000000000002',admin='00000000-0000-4000-8000-000000000003';
 await db.exec(`insert into auth.users values('${owner}'),('${stranger}'),('${admin}'); insert into admerest_private.reviewers(user_id) values('${admin}')`);
 const as=async(role,user)=>{await db.exec(`reset role; set role ${role}; select set_config('request.jwt.claim.sub','${user??''}',false);`);};
 const rows=async(sql)=>(await db.query(sql)).rows;
 const materials=JSON.stringify(Object.fromEntries(['5x6','5x8','5x10','6x12'].flatMap(s=>['hydrated','dry'].map(t=>[`${s}-${t}`,s==='5x6'&&t==='hydrated'?100:0]))));
 const create=async(verify=false)=>(await rows(`insert into public.admerest_submissions(display_name,country,cases,materials,period_end,verification_requested) values('검증 사용자','KR',200,'${materials}','2026-01-01',${verify}) returning *`))[0];
 await as('authenticated',owner);let row=await create(true);assert.equal(row.sheets,100);assert.equal(Number(row.length_m),6);
 await assert.rejects(()=>db.exec(`update public.admerest_submissions set status='approved',credential_checked=true,records_checked=true where id='${row.id}'`),/review|transition/i);
 await assert.rejects(()=>db.exec(`update public.admerest_submissions set status='submitted' where id='${row.id}'`),/evidence/i);
 await assert.rejects(()=>db.exec(`insert into public.admerest_public_records(id) values(gen_random_uuid())`),/permission/i);
 await as('anon');assert.equal((await rows('select * from public.admerest_public_records')).length,0);await assert.rejects(()=>rows('select * from public.admerest_submissions'),/permission/i);
 await as('authenticated',stranger);assert.equal((await rows('select * from public.admerest_submissions')).length,0);assert.equal((await rows(`update public.admerest_submissions set cases=999 where id='${row.id}' returning *`)).length,0);
 await as('authenticated',owner);
 for(const kind of ['credential','records']){const path=`${owner}/${row.id}/${kind}.pdf`;await db.exec(`insert into storage.objects(bucket_id,name) values('admerest-evidence','${path}'); insert into public.admerest_documents(submission_id,kind,object_path,filename,mime_type,size_bytes) values('${row.id}','${kind}','${path}','sample.pdf','application/pdf',100)`);}
 row=(await rows(`update public.admerest_submissions set status='submitted' where id='${row.id}' returning *`))[0];
 await assert.rejects(()=>db.exec(`update public.admerest_submissions set cases=999 where id='${row.id}'`),/locked/i);
 assert.equal((await rows(`delete from public.admerest_documents where submission_id='${row.id}' returning *`)).length,0);
 assert.equal((await rows(`delete from storage.objects where bucket_id='admerest-evidence' returning *`)).length,0,'submitted evidence cannot be deleted directly');
 await as('authenticated',stranger);assert.equal((await rows('select * from public.admerest_documents')).length,0);assert.equal((await rows('select * from storage.objects')).length,0);
 await as('authenticated',admin);await assert.rejects(()=>db.exec(`update public.admerest_submissions set status='approved' where id='${row.id}'`),/Verification/i);
 await db.exec(`update public.admerest_submissions set status='changes_requested',review_note='집계 기준을 보완해 주세요.' where id='${row.id}'`);
 await as('authenticated',owner);await db.exec(`update public.admerest_submissions set cases=250,status='submitted' where id='${row.id}'`);
 await as('authenticated',admin);await db.exec(`update public.admerest_submissions set status='approved',credential_checked=true,records_checked=true where id='${row.id}'`);
 await as('anon');let published=(await rows('select * from public.admerest_public_records'))[0];assert.equal(published.cases,250);assert.equal(published.verification,'verified');assert(!('owner_id' in published));
 await as('authenticated',owner);const revision=await create();await db.exec(`update public.admerest_submissions set cases=999,status='submitted' where id='${revision.id}'`);
 assert.equal((await rows(`update public.admerest_submissions set status='withdrawn' where id='${revision.id}' and version=0 returning *`)).length,0,'stale writes do not mutate the application');
 await as('anon');assert.equal((await rows('select * from public.admerest_public_records'))[0].cases,250,'pending changes cannot inherit existing verification');
 await as('authenticated',admin);await db.exec(`update public.admerest_submissions set status='approved' where id='${revision.id}'`);
 await as('anon');published=(await rows('select * from public.admerest_public_records'))[0];assert.equal(published.cases,999);assert.equal(published.verification,'none','unverified update cannot inherit badge');assert.equal((await rows('select * from public.admerest_public_records')).length,1,'stable public identity across updates');
 await as('authenticated',stranger);await db.exec('select public.admerest_hide_my_record()');assert.equal((await rows('select * from public.admerest_public_records')).length,1);
 await as('authenticated',owner);await db.exec('select public.admerest_hide_my_record()');
 await as('anon');assert.equal((await rows('select * from public.admerest_public_records')).length,0);
 await as('authenticated',admin);const own=await create(false);await db.exec(`update public.admerest_submissions set status='submitted' where id='${own.id}'`);await assert.rejects(()=>db.exec(`update public.admerest_submissions set status='approved' where id='${own.id}'`),/locked/i);
 await db.close();
});
